### ISSUE TITLE
why doesn't it buy barns automatically?

### ISSUE THREAD

**Issue by jlb0170** [cameroncondry/cbc-kitten-scientists#1]

**Comment by cameroncondry** [comment]
The system does build barns automatically. However, barns are the lowest in priority, meaning, there must be more than 75% of the max wood available, and all other buildings that auto build while taking wood must already be built. It definitely feels slow though, since there are a lot of buildings before it. I've been debating moving to a more definitely auto building scheme.

**Comment by jlb0170** [comment]
man, if it can build a barn, i don't know what would be higher priority.

On Wed, Mar 4, 2015 at 4:40 PM, Cameron Condry <notifications@github.com>
wrote:

> The system does build barns automatically. However, barns are the lowest
> in priority, meaning, there must be more than 75% of the max wood
> available, and all other buildings that auto build while taking wood must
> already be built. It definitely feels slow though, since there are a lot of
> buildings before it. I've been debating moving to a more definitely auto
> building scheme.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cameroncondry/cbc-kitten-scientists/issues/1#issuecomment-77266201>
> .
>



-- 
Regards, Jeff

**Comment by cameroncondry** [comment]
Currently the system waits for pasture, library, academy, and mines before building a barn. Barns do not actually contribute to any resource growth, and the system favors production over storage.

**Comment by jlb0170** [comment]
that makes sense. barn isn't listed on the help page, thus my confusion.

On Wed, Mar 4, 2015 at 4:47 PM, Cameron Condry <notifications@github.com>
wrote:

> Currently the system waits for pasture, library, academy, and mines before
> building a barn. Barns do not actually contribute to any resource growth,
> and the system favors production over storage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cameroncondry/cbc-kitten-scientists/issues/1#issuecomment-77267373>
> .
>



-- 
Regards, Jeff

**Comment by cameroncondry** [comment]
I noticed that as well, it has been added, thank you.

**Comment by jlb0170** [comment]
if it wasn't obvious, THANK YOU FOR THE TOOL! very helpful.

On Wed, Mar 4, 2015 at 4:52 PM, Cameron Condry <notifications@github.com>
wrote:

> I noticed that as well, it has been added, thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cameroncondry/cbc-kitten-scientists/issues/1#issuecomment-77268271>
> .
>



-- 
Regards, Jeff

**Comment by cameroncondry** [comment]
No problem, excited to see people using it. Let me know if you find anything else.

**Comment by jlb0170** [comment]
i was wondering if you could make it easy to say like [next building:] with
a text box and "Amphitheatre" or "Log House" and it would stop using
resources or building until it could build that building for you

more complex i know.

On Wed, Mar 4, 2015 at 4:56 PM, Cameron Condry <notifications@github.com>
wrote:

> No problem, excited to see people using it. Let me know if you find
> anything else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cameroncondry/cbc-kitten-scientists/issues/1#issuecomment-77268857>
> .
>



-- 
Regards, Jeff

**Comment by cameroncondry** [comment]
That could be a neat feature, the engine already has a method to pause itself. I'll definitely note that idea.

**Comment by jlb0170** [comment]
another quick question - why is the parchment limit set so high on making
manuscripts? it seems like there isn't any reason to keep such a large
supply of parchment around before making manuscripts?

On Wed, Mar 4, 2015 at 5:50 PM, Cameron Condry <notifications@github.com>
wrote:

> That could be a neat feature, the engine already has a method to pause
> itself. I'll definitely note that idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cameroncondry/cbc-kitten-scientists/issues/1#issuecomment-77276807>
> .
>



-- 
Regards, Jeff

**Comment by cameroncondry** [comment]
The limit is due to buildings and a science requires 2500 parchments. Early game that is a bit high if you are looking to have manuscripts. I wonder if I could do some sort of scale based on the amount of cats you have... *trails off*
