### ISSUE TITLE
Luxury does not craft Manuscripts

### ISSUE THREAD

**Issue by magus424** [cameroncondry/cbc-kitten-scientists#10]
I am consistently finding myself at max culture with tons of parchment. The scientists don't seem to like hitting the Manuscript button ;)

**Comment by magus424** [comment]
I stand corrected; after passing 700 parchments, it *finally* made some manuscripts: is there an additional limit other than just % of culture?

**Comment by cameroncondry** [comment]
The system tries to keep a certain number of parchments on hand for purchasing buildings and science that require parchments. The current limit is 500, it tries to keep at least 500 parchments on hand before crafting manuscripts. The same goes for compendiums, 500 manuscripts must be on hand before crafting them.

**Comment by magus424** [comment]
Sorry to ping again, but it's happening again with 1800+ parchments;

![culture/parchment issue](http://i.imgur.com/FuOaxr7.png)

**Comment by cameroncondry** [comment]
It only crafts right before it sends out a hunt. I'm planning on making it happen more often, but havent had the time to update the script properly.

**Comment by magus424** [comment]
Ah, I see; it uses the same trigger as parchments then
