### ISSUE TITLE
Not auto hunting when crafting is enabled

### ISSUE THREAD

**Issue by vikusz** [cameroncondry/cbc-kitten-scientists#100]
I refreshed Kittens game and Kitten Scientists today and was surprised to see that auto hunting stopped working. I managed to get it work but only if crafting is disabled. Crafting works (if enabled) regardless of the hunting checkbox state.
The same bug(?) applies to trading. Trading only works with crafting disabled.
I tried clearing the cache, cookies, etc. and reconfiguring Kitten Scientists but this did not solve the problem.
Auto crafting is triggered every 1-2 second in my current game, this may have something to do with not executing the hunts and trades.

EDIT: getting this error in the console:
    TypeError: this.getCraft(...) is null kitten-scientists.js:532:22
    Failed to get craft for id 'kerosene'
Obviously KS can't get the kerosene info because I'm not playing the beta. Could this be connected to why auto hunting and trading don't trigger?

EDIT2: It seems that Eludium crafting isn't working. I suppose Eludium is crafted after Kerosene in the code so the addition of Kerosene could cause these troubles.

**Comment by oliversalzburg** [comment]
Trading did not work at all for quite some time. That should be fixed by #102 
Kerosene should be released as of now (1.1.5.2)

Can you still reproduce this?

**Comment by vikusz** [comment]
Did a little testing, the results are even weirder now. I had the crafting and hunting checkboxes checked all the time.
Crafting works as expected (except for Eludium crafting, but I haven't tested it too much, my unobtainium storage fills too slowly).
As for hunting, for some time period it works perfectly ( for about 5-10 minutes). Then, without me intervening with KS, the auto hunting stops working and it doesn't work for 5-10 minutes. After some time it starts working again and the cycle repeats itself.
During the time auto hunting works, the console is clear. When it doesn't work, the console is being spammed with the error in the OP every 2-3 seconds.

**Comment by oliversalzburg** [comment]
Can you try https://github.com/cameroncondry/cbc-kitten-scientists/pull/105 and see if that makes a difference?

**Comment by vikusz** [comment]
I can confirm that Crafting (including Eludium), Hunting, and Trading now work simultaneously.
The error "Failed to get craft for id 'kerosene'" still appears in the console from time to time, although only about every two minutes.
It seems that now KS is working as expected. Great job with the quick fix!

**Comment by vikusz** [comment]
Closing the issue.
