### ISSUE TITLE
Absence Report Feat. Request

### ISSUE THREAD

**Issue by mmccubbing** [cameroncondry/cbc-kitten-scientists#11]
Would love to see an absence report functionality that would give a summary of what happened while I was away. Having a simple button that triggers the report and pulls up a pop-over that shows a summary of the number of buildings built, special events, etc would be awesome as the log is fairly short and even a short absence can leave items off screen.

**Comment by cameroncondry** [comment]
That would be a really nice and fun feature to make. Once I knock out some of the more outstanding issues, then I think I'll start on these nice to have features.

**Comment by jacob-keller** [comment]
Yea, this would be pretty handy. I'm not sure the best way to store or display this data, but definitely would be useful.

**Comment by cameroncondry** [comment]
This has been implemented on master thanks to @jacob-keller
