### ISSUE TITLE
Does the version number need to be increased for auto-update?

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#110]
What is needed that Tampermonkey/Greasemonkey will update the script? I'm not too familiar with this part of userscripts, but I don't think automatic updates were triggered by the latest changes.

**Comment by cameroncondry** [comment]
Ideally the version number should be incremented with each PR merge. However, I haven't spent the time updating the changelog or version numbers when I'm merging in since I do not actively play at this time. Waiting for a big release before I get back into it again.

**Comment by oliversalzburg** [comment]
Closing in favor of #133
