### ISSUE TITLE
Remove or make CSS adjustments optional

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#122]
I had a look at the Sleeky Theme in 1.1.7.8:
![](https://i.imgur.com/EP4fdak.png)

It seems like the Scientists CSS adjustments are conflicting with it. Given the issues that are caused by the CSS adjustments in regards to button labels and the potential conflicts with other themes, I would propose that the CSS adjustments should be removed from the script.

Users who want to keep them, should be able to apply them by other means (Like Stylish, Stylebot, or other userstyle extensions).

I could even see adding a button that makes the adjustments on demand, but I think the automation and presentation features should be separated.

**Comment by cameroncondry** [comment]
If people or the creator are making better themes for the system, then I am all for removing the css tweaks in kitten scientists. May be fun to offer an option system that will pull in other themes that have been hosted through github.

**Comment by oliversalzburg** [comment]
Oh god, I just removed the CSS and saw the default theme again. Haven't seen that in a long time. What a disaster!

Maybe styling could be applied conditionally, depending on the value of `gamePage.colorScheme`.
