### ISSUE TITLE
Suggestion: Change default build priority

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#131]
Originally, I wanted to allow the user to reorder build items to change which are built first, but this turns out to be very complicated.

I wanted to do this because I found the current order not optimal. For example, science and storage buildings are prioritized before housing. This has the effect that academies and barns are built before huts in early stages of the game. This is frustrating, because you need every single kitten to get your game started.

I've changed the order in my fork and have been happily using it ever since and I would like to know if there is interest to adapt this order upstream.

The current order is:

1. Science
2. Craft Bonuses
3. Production
4. Conversion
5. Storage
6. Housing
7. Other

My proposed order is:

1. Housing  
   *Is promoted to the top spot. If there is any possibility to get more kittens, it should be built.*
2. Craft Bonuses
3. Production
4. Conversion
5. Science  
  *Demoted below all buildings that affect resources. The reasoning is that you would want to max out production within your current science cap before you want to extend the science cap and research new technologies.*
6. Other
7. Storage  
  *Demoted to lowest priority. KS should build whatever it can within the current storage cap before it spends resources on extended the storage cap.*

I would have sent this within a PR, but creating the PR will be a lot easier if #130 is merged.

**Comment by cameroncondry** [comment]
I would be fine with the proposed update. It maximizes each step in the game instead of trying to hopscotch up in power. There are a lot more options that have been added since I made up the original order, so it is definitely due for a bit of a change up.

**Comment by oliversalzburg** [comment]
Awesome. I'll prepare a PR when the existing PRs have settled. :)

**Comment by Ramdat** [comment]
I would suggest that you also add a feature to automatically assign newly born kittens to a specified job. Thus, kittens born from autobuilding are not useless if you are AFK.

Speaking of kittens, it would be nice to have a proper scroll list on the Census section to see all the kittens instead of only 10 of them. There is a filter for jobs, but it still only shows 10 of them in that list.

**Comment by oliversalzburg** [comment]
@Ramdat Please open a separate ticket for every requested feature. That makes it easier to keep track of them.

I never understood why the census only lists 10 kittens. But, then again, it really doesn't matter which kitten you pick.

**Comment by Ramdat** [comment]
@oliversalzburg Alright. I'm not very familiar with GitHub, my apologies. 

It does if you make mistakes while moving kittens from other jobs. For example, if you move Master Woodcutters and Master Hunters to Geology, and then return them to their jobs in the wrong order, you waste their experience bonuses. Although it is fairly easy to manage them if you remember the quantity and order, it would be a good feature nonetheless.

**Comment by oliversalzburg** [comment]
@Ramdat Ah, I see your point. Thanks for the suggestion :)
