### ISSUE TITLE
Resource crafting

### ISSUE THREAD

**Issue by Aitch3** [cameroncondry/cbc-kitten-scientists#135]
I have found that some resources will not auto-craft until you disable it and then enable it again. I'm not doing a normal one, so I have much more limited resources for doing testing.

**Comment by oliversalzburg** [comment]
[Related Reddit post](https://www.reddit.com/r/kittensgame/comments/3z1zc5/new_to_kitten_scientists/)

**Comment by oliversalzburg** [comment]
@Aitch3 Is it possible that the trigger threshold was simply not reached yet? Maybe this is linked to #70

**Comment by Aitch3** [comment]
I don't think so. Unless there is some part of the code that says it won't
auto-craft manuscripts if Max Culture isn't above a certain amount.

I was sitting at my current culture capacity and it wasn't crafting. After
disabling and enabling manuscript creation using the specific checkbox, it
started working. The same thing occurred for steel and plates.

**Comment by Wymrite** [comment]
Likely caused by the enable-all bug.
