### ISSUE TITLE
Issues with getTradeButton

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#139]
Occasionally, I see the following message in the DevTools console: `Uncaught TypeError: Cannot read property 'hasResources' of undefined` referring to `getTradeButton`. Above that message, I always see an entry with `Array[2]`.

This brings up several issues:
- The `warning` function does not work as expected or is used incorrectly. The passed arguments array is not logged correctly.
- There is some condition when `getTradeButton` does not work as expected.
- The `warning()` call in `getTradeButton` references the undefined variable `name`, which should probably be `race` instead.

**Comment by Wymrite** [comment]
Fixed as of #248
