### ISSUE TITLE
Bug: Space autobuild creates locked structures

### ISSUE THREAD

**Issue by Ramdat** [cameroncondry/cbc-kitten-scientists#152]
Space autobuild can create space structures before the appropriate mission and technology is unlocked. For example, it can build Space Elevator before Orbital Engineering and Orbital Launch, Sunlifters before Helios mission, Lunar Outposts before the Moon Mission and so on.

**Comment by oliversalzburg** [comment]
Whoops. I feared that this might be possible. I'll look into it!

**Comment by Wymrite** [comment]
Should not be possible in current version.
