### ISSUE TITLE
Trade Trigger=0 for "always trade"

### ISSUE THREAD

**Issue by drharris** [cameroncondry/cbc-kitten-scientists#153]
In IW mode, you have to do a lot of trading ivory->minerals. Since ivory doesn't have capacity, no trigger value seems to put it in a mode where it will always trade when available. I suggest a trigger of 0 to mean "always trade when able to". Or else there should be a way to specify that option for certain trade routes.

**Comment by Wymrite** [comment]
Functional for some time now, not completely lag inducing since #256
