### ISSUE TITLE
Too many enable/disable messages in log

### ISSUE THREAD

**Issue by GronbergInfo** [cameroncondry/cbc-kitten-scientists#155]
Lets say for example, i open items under building, i click "enable all".
_I_ think that the each building that changes status should only get into the log. 
Buildings that already are enabled shouldnt give a status change:

ALSO, when i click "enable all".. WHY do i get a BUNCH of "disabled ...." messages?

Enabled Auto Warehouse
Enabled Auto Harbour
Enabled Auto Barn
Enabled Auto Chronosphere
Enabled Auto Ziggurat
Enabled Auto Unic. Pasture
Enabled Auto Mint
Enabled Auto Temple
Enabled Auto Chapel
Enabled Auto Tradepost
Enabled Auto Broadcast Tower
Enabled Auto Amphitheatre
Enabled Auto Observatory
Enabled Auto Academy
Enabled Auto Library
Enabled Auto Magneto
Disabled Auto Steamworks
Disabled Auto Accelerator
Disabled Auto Reactor
Disabled Auto Calciner
Enabled Auto Bio Lab
Disabled Auto Smelter
Enabled Auto Quarry
Enabled Auto Oil Well
Enabled Auto Hydro Plant
Disabled Auto Aqueduct
Enabled Auto Lumber Mill
Enabled Auto Mine
Enabled Auto Solar Farm
Disabled Auto Pasture
Disabled Auto Catnip field
Enabled Auto Factory
Enabled Auto Workshop
Disabled Auto Mansion
Disabled Auto Log House
Disabled Auto Hut
Disabled Auto Warehouse
Disabled Auto Harbour
Disabled Auto Barn
Disabled Auto Chronosphere
Disabled Auto Ziggurat
Disabled Auto Unic. Pasture
Disabled Auto Mint
Disabled Auto Temple
Disabled Auto Chapel
Disabled Auto Tradepost
Disabled Auto Broadcast Tower
Disabled Auto Amphitheatre
Disabled Auto Observatory
Disabled Auto Academy
Disabled Auto Library
Disabled Auto Magneto
Enabled Auto Steamworks
Enabled Auto Accelerator
Enabled Auto Reactor
Enabled Auto Calciner
Disabled Auto Bio Lab
Enabled Auto Smelter
Disabled Auto Quarry
Disabled Auto Oil Well
Disabled Auto Hydro Plant
Enabled Auto Aqueduct
Disabled Auto Lumber Mill
Disabled Auto Mine
Disabled Auto Solar Farm
Enabled Auto Pasture
Enabled Auto Catnip field
Disabled Auto Factory
Disabled Auto Workshop
Enabled Auto Mansion
Enabled Auto Log House
Enabled Auto Hut

**Comment by Wymrite** [comment]
Fixed as of #248
