### ISSUE TITLE
Dont trade if...

### ISSUE THREAD

**Issue by GronbergInfo** [cameroncondry/cbc-kitten-scientists#162]
I just noticed, that Ks trades for titaniums, my max storage is 4-5 million.
but each trade gives me 4G! 

It would probably be better, if the game seems i have lets say >95% storage of said resource, DONT trade for it, since it most likly will trade tons of stuff for nothing and wating catpower.

**Comment by oliversalzburg** [comment]
There's actually code for that already in KS. It's possible that either another resource the race trades can be got (like Blueprints, which has no cap) or you simply get so many resources from ship bonuses, that there isn't any lower amount to get.

**Comment by Wymrite** [comment]
Intended behavior, KS intentionally caps resources with trade, even if one trade will give far over the cap.
