### ISSUE TITLE
https://rawgit.com times out. KS stopped working

### ISSUE THREAD

**Issue by GronbergInfo** [cameroncondry/cbc-kitten-scientists#167]
https://rawgit.com times out. KS stopped working

**Comment by oliversalzburg** [comment]
It seems to work now. However, I would suggest that we change to https://cdn.rawgit.com/cameroncondry/cbc-kitten-scientists/master/kitten-scientists.user.js to comply with rawgit.com guidelines.

**Comment by Wymrite** [comment]
No longer relevant as KS now uses jsdelivr.
