### ISSUE TITLE
Broken in 1.2.0.0

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#171]
The game is now loaded asynchronously, which causes `gamePage` to not be available when the script is started.

**Comment by zelenay** [comment]
Hello,

I have solved this by creating timer that checks if gamePage is available and load plugin after that.

See:

https://github.com/zelenay/cbc-kitten-scientists/blob/master/kitten-scientists.user.js

**Comment by cameroncondry** [comment]
That looks like a solid solution for this issue. If you want, clean up the function a bit and issue a PR and I will get it merged into the master branch. Thank you.
