### ISSUE TITLE
Newest change seems to be preventing the game from updating the "purchasable" state of buildings

### ISSUE THREAD

**Issue by quinnrdavis** [cameroncondry/cbc-kitten-scientists#173]
Since the change a couple days ago I've had issues with buildings not lighting up and becoming available to purchase when I reach the correct amount of resources.  Hovering over the building will show all of the resources as white (inverted color scheme) and over the required amount but the building will still be gray and clicking on it does nothing.  Buying a building that was already available to purchase before I ran the script seems to force it to recheck and then the buildings will be purchasable.  It also happens the other way, if I have enough to buy a building and then for example I craft steel and no longer have enough iron it will still show the building as purchasable, clicking on it does nothing though.  I'm using chrome.

edit: I should add it doesn't seem to be happening with workshop upgrades, I don't have any science upgrades to test in my current game.

**Comment by oliversalzburg** [comment]
Since the latest update, I noticed that the building count will not increase when buildings are purchased, even though the building *is* purchased. I assume this is an issue with the game itself.

Regarding buildings not automatically being purchased, buildings will only by purchased when the set trigger allows them to be built. By default, the required resources need to be close to the storage max for a building to be purchased. This can be configured by clicking the **trigger** link.

**Comment by elbo444** [comment]
I haven't noticed anything with automation, I'm talking about manually purchasing buildings.  I'm not having the problem when not running the script, and it's a little different than what you describe.  If I buy a building that is purchasable and force it to update the other building to be purchasable when they should be, I can then buy those buildings and the number will increase.  Also when the buildings show as not purchasable but they actually should be, clicking on them does not spend resources or increase whatever the building would increase so I don't think they're actually being purchased.

**Comment by oliversalzburg** [comment]
Yeah, I'm experiencing the same behavior. I guess I falsely assumed that it's a bug in the game.

**Comment by poizan42** [comment]
Curiously this issue seems to have gone away again in 1.3.0.0.

**Comment by Gavitron** [comment]
I have this issue on v1.3.1.0 w/ KS v1.3.1,  but for anyone having the issue, clicking on any inactive button will refresh the button states and enable any "missing" buttons.

**Comment by amaranth** [comment]
Should be fixed as of commit b400ccb5.
