### ISSUE TITLE
Missing space buildings.

### ISSUE THREAD

**Issue by woutershep** [cameroncondry/cbc-kitten-scientists#176]
Containment Chamber and Terraforming Station are not in the list of 'items'.

**Comment by poizan42** [comment]
A bit more generally perhaps, but why don't we just get the buildings directly from the game instead of hardcoding them? The required resource system would have to be improved at the same time to handle all the required resources with limits on them - is there any issues with that?

**Comment by oliversalzburg** [comment]
In general, I see no problem with that. I just assume it would require a lot of refactoring to make it work.

**Comment by Erlemar** [comment]
I did it in my local version (in Tampermonkey).
I simply added the following lines in the space items:
                    // Yarn
                    terraformingStation:    {require: 'antimatter',  enabled: false},
                    // Centaurus System
                    tectonic:    {require: 'antimatter',  enabled: false}

It works locally.
