### ISSUE TITLE
Auto-festival only triggers if City tab is open

### ISSUE THREAD

**Issue by alex-gonz** [cameroncondry/cbc-kitten-scientists#184]
As in title. When not in the city tab, festivals aren't triggering.

**Comment by binaryalgorithm** [comment]
I think the enabled state of the festival button is only updated when the tab is activated. It may be helpful to change the logic to check for the specific conditions instead (5000 culture, 1500 catpower, and 2500 parchment).

**Comment by amaranth** [comment]
Is this still a problem after commit 65e5e787?

**Comment by Wymrite** [comment]
Appears to have been fixed as of #213
