### ISSUE TITLE
Auto festival & auto trading no longer functioning

### ISSUE THREAD

**Issue by metalax** [cameroncondry/cbc-kitten-scientists#193]
Auto festival is no longer functioning following the most recent update. This is also causing KS to hold at that point and not process auto crafting or auto building. If a festival is triggered manually, crafting and building resumes until the festival ends. Disabling auto festival also allows crafting and building to proceed.

Similarly auto trading is not functioning and is blocking auto hunting from occurring. Disabling auto trading allows auto hunting to resume. This is also reliant on having either manually triggered a festival or disabled auto festival, otherwise auto hunting is still blocked.

**Comment by riannucci** [comment]
The stacktrace for the festival error is

```
Uncaught TypeError: this.villageManager.tab.festivalBtn.hasResources is not a function
    at Engine.holdFestival (kitten-scientists.user.js:466)
    at Engine.iterate (kitten-scientists.user.js:387)
```

**Comment by riannucci** [comment]
I suspect that the incompatibility was introduced here: https://bitbucket.org/bloodrizer/kitten-game/commits/6c260d2c2f06872affa3f6de9d2f7d17e3019262

but it's a pretty huge commit :)

**Comment by riannucci** [comment]
I suspect that `game.villageTab.festivalBtn.model.enabled` can be used to determine if the button is currently enabled or not in the current version of kg.

**Comment by riannucci** [comment]
Yeah it looks like all the various buttons changed from `...Btn.hasResources()` to `...Btn.model.enabled` booleans. I haven't confirmed that this is afflicting the other ks functions, but reading the code implies that it is. I'll see if I can hack up a fix.

**Comment by riannucci** [comment]
that said, auto-building doesn't seem to be working either... I suspect someone more familiar than myself will need to go through ks to fully adapt it to the new version.

**Comment by Darael** [comment]
For auto-trading, the `tradeMultiple` function on the button is gone, but the functionality is still there - `gamePage.diplomacy.tradeMultiple(race,amount)` is what's needed for the quick-and-dirty fix, at least.

**Comment by mwdiers** [comment]
Auto Hunting is also broken, and auto crafting is spotty at best.

**Comment by metalax** [comment]
Looks like the recent updates have fixed these issues, as far as I've been able to test.
