### ISSUE TITLE
Log entries are overwritten by KG

### ISSUE THREAD

**Issue by mwdiers** [cameroncondry/cbc-kitten-scientists#197]
Auto hunt no longer displays a status in the log. Other statuses, such as auto-crafting, are still working.

**Comment by mwdiers** [comment]
Changing the title as this appears to be a general problem. Anything KS writes to the log is overwritten by the next log update from KG. This in the case of Auto-hunt, the KG hunting results entry overwrites the corresponding KS log entry.

**Comment by coderpatsy** [comment]
Should be fixed by PR #196
