### ISSUE TITLE
Trading with Leviathans only occurs when tab is open.

### ISSUE THREAD

**Issue by afxwinter** [cameroncondry/cbc-kitten-scientists#206]
I've noticed that trading is now working again since the last pull however it only occurs when the trade tab is open.

**Comment by afxwinter** [comment]
Am I the only one having this issue?  It's a bit annoying smashing time crystals and then having to keep popping into the trade tab so the trades occur.

**Comment by catattacktack** [comment]
I'm having the same problem.  I traced down the code to line 773:
if (!button.model.enabled || !options.auto.trade.items[name].enabled) return;

for whatever reason, button.model.enabled returns false, even when it should be true.  Thus KS aborts the trade.  I don't think the "!button.model.enabled" is need, so I "fixed" it by just removing that part of the line.  Now KS works fine, but I'm not sure that it is safe to remove that.  Hopefully someone with more knowledge will look into it.

**Comment by Wymrite** [comment]
@cameroncondry This issue has been fixed for awhile. There's a lot of open issues/suggestions that had either been fixed or implemented long ago. I don't know too much about github, but I'd be willing to go through and close the outdated ones if there is some way for you to give me that permission.

**Comment by cameroncondry** [comment]
I like that idea. I think I've given you the proper permissions, just need to accept the invite. 👍
