### ISSUE TITLE
Trade filter doesn't appear

### ISSUE THREAD

**Issue by BrianMcErlean** [cameroncondry/cbc-kitten-scientists#207]
The trade filter doesn't appear in the list of filters.  It looks like changing the place this was added from `game.console.static.filters.trade` to just `game.console.filters.trade` resolves it.

**Comment by amaranth** [comment]
Should be fixed after commit 3221f680.

**Comment by Wymrite** [comment]
KS no longer handles filters regardless. (Though maybe it should).
