### ISSUE TITLE
Auto-Festival not working with 1.4.0.8

### ISSUE THREAD

**Issue by mwdiers** [cameroncondry/cbc-kitten-scientists#209]
Even when on the Bonfire tab, it doesn't fire.

**Comment by krisavi** [comment]
It also spams quite many console errors.

```
Uncaught TypeError: Cannot read property 'festivalBtn' of undefined
    at Engine.holdFestival (kitten-scientists.user.js:424)
    at Engine.iterate (kitten-scientists.user.js:345)

```

It seems the festivalBtn is now game.villageTab.festivalBtn while before it seemed to be game.villageManager.tab.festivalBtn

**Comment by mwdiers** [comment]
It is maintained. It just doesn't need updates until the game revs.

**Comment by mwdiers** [comment]
That worked. The relevant section:

`holdFestival: function () {
            if (game.science.get('drama').researched && game.calendar.festivalDays === 0 && game.villageTab.festivalBtn.model.enabled) {
                game.villageTab.festivalBtn.onClick();

                if (game.calendar.festivalDays !== 0) {
                    storeForSummary('festival');
                    activity('Kittens begin holding a festival', 'ks-festival');
                }
            }
        },`

**Comment by sickhippie** [comment]
The only thing that seems to be working for me is auto-praise.  Auto-buy and auto-craft aren't firing at all.

**Comment by Saucistophe** [comment]
@sickhippie I had that too, but either manually starting a festival or disabling the auto-festival fixes everything.

**Comment by cameroncondry** [comment]
@mwdiers I don't personally maintain the code base currently. However, there are a number of other players that keep the system updated and you're more than welcome to make corrections/modifications if you want. I try my best to keep PRs merged, but do rely heavily on the requesters to test the modifications before I merge them. Either way, glad you, and others, are still actively trying the script.

**Comment by sickhippie** [comment]
There's some issues with auto-space too, the "enable all" button will show enable then disable messages in the game log.  If no one else has PR'd this by the weekend I'll take a crack at fixing it up.

**Comment by TomRauchenwald** [comment]
I think something broke with that merge.
Looks like in line 433 a comma went missing, so KS doesn't load anymore:
`holdFestival: function () {
            if (game.science.get('drama').researched && game.calendar.festivalDays === 0 && game.villageTab.festivalBtn.model.enabled) {
                game.villageTab.festivalBtn.onClick();
                if (game.calendar.festivalDays !== 0) {
                    storeForSummary('festival');
                    activity('Kittens begin holding a festival', 'ks-festival');
                }
            }
        }
    ^^^^^
        observeStars: function () {`

**Comment by relomy** [comment]
Personally, I tried changing to `game.villageTab` and I believe I had the same issue if you do not visit the village tab at some point because it cannot tell if the model is enabled. I found the easiest fix was on line 320 changing `'Small Village'` to `'Village'`.

**Comment by amaranth** [comment]
This is fixed now, right?

**Comment by Wymrite** [comment]
Appears that the proposed fix long ago worked.
