### ISSUE TITLE
Alloy crafting nukes steel reserves

### ISSUE THREAD

**Issue by mmccubbing** [cameroncondry/cbc-kitten-scientists#21]
With my current production & auto trading my titanium is almost always maxed out and this means that alloy crafting is constantly triggering preventing me from building up a steel reserve for crafting any further buildings. Each day half of my steel is consumed for alloy crafting until I have <150 remaining. Other than disabling crafting altogether, which isn't much of a solution either as it's the quickest way to build up that steel in the first place, I don't have a way to prevent every last bit of steel from being converted into alloy.

**Comment by sjdrodge** [comment]
I agree that the alloy crafting policy is not a particularly good default. As a short term solution, you can simply execute the following in your javascript console: `options.auto.craft.pop();` This will remove the last entry in the auto-crafting rules, which (at least for now) is the alloy rule that you want to get rid of.

**Comment by cameroncondry** [comment]
Thank you for that temporary solution, I'm pushing to get a more refined set of options available for users that let you enable/disable crafting as needed.

**Comment by mmccubbing** [comment]
Thank you, @sjdrodge, that works beautifully.

@cameroncondry: Would this be done by turning the current "Crafting" checkbox into a link that opens a small pop-up with options to toggle each recipe? That would be amazingly useful.

**Comment by cameroncondry** [comment]
@mmccubbing Something along those lines, I'm thinking all the current list items will become a click handler that will slide out the options for the different sections. Make it so you can expand and check all your options, then hide them away. The main road block was there are just so many options, and it became extremely clutters having them always on.

**Comment by jacob-keller** [comment]
I agree. Originally added it as a method of preventing cap on limited resources.

We could also add a limit on steel so that it doesn't get drained too much?

**Comment by cameroncondry** [comment]
The limit for steel is in the master branch, however, this will only help with the early game steel use. Later game has buildings requiring much more steel than this holds on hand.
