### ISSUE TITLE
New issues with latest commit

### ISSUE THREAD

**Issue by merberry** [cameroncondry/cbc-kitten-scientists#216]
Sorting by job type gives blanks
![image](https://user-images.githubusercontent.com/28709343/27353481-294fea2c-55d2-11e7-8b14-1f7869233dca.png)
Buildings don't show as craftable when the correct accumulated resources are amassed
Free kittens on village tab doesn't update when they are assigned
Just went a bit buggy today.

**Comment by merberry** [comment]
![image](https://user-images.githubusercontent.com/28709343/27353688-fbc1e258-55d2-11e7-94fc-c7f8dc702555.png)
Screenshot showing 1 kitten still available but I just added that last miner (numbers don't tally)

**Comment by amaranth** [comment]
Is this still happening after commit b400ccb5?

**Comment by merberry** [comment]
Nope it looks like everything is fixed, thanks!
