### ISSUE TITLE
Leader bonus not working on Kitten Scientist crafted goods

### ISSUE THREAD

**Issue by Arumba07** [cameroncondry/cbc-kitten-scientists#218]
Working as intended?

When my 'Scientists' do the task:
![image](https://user-images.githubusercontent.com/27012898/28226224-5c5142a2-68a3-11e7-89fc-fef1d4c384b6.png)

When I do the task:
![image](https://user-images.githubusercontent.com/27012898/28226328-b665137c-68a3-11e7-8005-bfb3a2e361df.png)

This is with a leader with the Artisan (crafting bonus) skill:
![image](https://user-images.githubusercontent.com/27012898/28226309-a74800fc-68a3-11e7-9ca2-2c26df415e51.png)

I'm not sure I understand why the bonus wouldn't apply.  Is it just this leader bonus?  Do the others work?

**Comment by Phoenix09** [comment]
I see why this happens.

https://github.com/cameroncondry/cbc-kitten-scientists/blob/d9fd43f72274215df3cb4a14874c0ce8b066c91c/kitten-scientists.user.js#L701#L706
The bonus is only being calculated from `craftRatio`, but there's more that affects it.

Really we should be using `game.getResCraftRatio(res)` so it includes all crafting bonuses.
https://bitbucket.org/bloodrizer/kitten-game/src/bc6362ba4d8c825ff60edab2f48c1e72d1f94d3f/game.js?fileviewer=file-view-default#game.js-2451:2477
https://bitbucket.org/bloodrizer/kitten-game/src/bc6362ba4d8c825ff60edab2f48c1e72d1f94d3f/js/workshop.js?at=master&fileviewer=file-view-default#workshop.js-2098:2100

Also, I believe this doesn't affect the amount crafted, only the value displayed in the log.
