### ISSUE TITLE
Suggestion: toggle to make Building respect Crafting stock quantities.

### ISSUE THREAD

**Issue by kaeroku** [cameroncondry/cbc-kitten-scientists#224]
Useful for situations wherein, ie, you're looking to build a hut which costs nearly your wood capacity. You can set Wood stock to the exact amt. required for the building, and it will hold until it has that many (and never craft below) so when you come back, you can manually purchase the hut if it hasn't auto-built by then.

Thanks for your consideration!

Edit: added benefit to this would be that, for instance, we could set Catnip stock at 10k (or whatever) so that when the script wants to spend all your catnip to buy the next level of pasture, it won't do this. Which potentially helps keep the script from killing all your kittens in the Winter, which just happened to me. XD.

**Comment by eykanal** [comment]
Fixed by #226.
