### ISSUE TITLE
Skript stops working with building enabled

### ISSUE THREAD

**Issue by L0ric0** [cameroncondry/cbc-kitten-scientists#228]
As Title says the Skript stops working when building is enabledwith this error:
TypeError: bld is undefined
getPricesWithAccessor     http://bloodrizer.ru/games/kittens/js/buildings.js:1768:8
getPrices                          http://bloodrizer.ru/games/kittens/js/buildings.js:1764:10
build                                https://rawgit.com/cameroncondry/cbc-kitten-scientists/master/kitten-scientists.user.js:417:34
iterate                              https://rawgit.com/cameroncondry/cbc-kitten-scientists/master/kitten-scientists.user.js:364:45
iterate self-hosted:948:17

**Comment by Kobata** [comment]
This is what I tried to fix in #229, so it might be working now.

**Comment by L0ric0** [comment]
Yes it is woking now. Thanks
