### ISSUE TITLE
Truncate log

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#261]
When automatically trading, several trades happen every second for me. This _very_ quickly fills the log with a ton of entries.

After a minute, the performance of the tab running KG has severly degraded. When switching between tabs, it's not uncommon for the KG tab to be frozen for an extended period of time until it becomes responsive again. This is due to the poor performance of the log.

I propose that KS should try to manipulate the log view and trim it to X entries to resolve this issue.

**Comment by Wymrite** [comment]
It's funny that you mention this now because as of 2 days ago, I pushed an update to KG's logging system to pretty much completely eliminate it's lag. Website isn't updated yet, but the master branch on the repository is and using it has eliminated KG's lag for me.

**Comment by oliversalzburg** [comment]
Just gave it a try. That looks really nice. Feels much more responsive!

**Comment by oliversalzburg** [comment]
For anyone else desperately waiting for this to be fixed, put this in the DevTools console:

```js
setInterval(()=>gamePage.clearLog(),1000)
```

**Comment by cameroncondry** [comment]
It looks like commit 29b3ff2 should correct this issue.

**Comment by Wymrite** [comment]
The fix is actually on KG's end. The website just hasn't been updated yet to match KG's repository.

**Comment by oliversalzburg** [comment]
Yeah, I'm waiting for this to be fixed upstream, but the trading/crafting is happening at such an insane volume for me currently, that the UI becomes practically unusable after like 30 seconds.

I guess it could also be nice if the log filters actually applied to the game events to hide those messages. They have no value at all at such a high frequency and you can't see the actually relevant events. Even when you use the "Show activitiy" action, it's pushed out of view in a few seconds.

The usability of the log at this stage is really problematic. I wish I could work on it, but I have set my sight on a different issue I need to look into :D

**Comment by Wymrite** [comment]
There are in-game filters as well, so it is possible to just use those to hide trading and crafting messages as well. I didn't originally include them in the messages filtered by KS's filters because I thought there might be cases where people may want to see any manually done crafting/trading. If I'm overlooking something here, it should be fairly straightforward to change, maybe have it quickly toggle KG's relevant in-game filter on and off when trading/crafting?

**Comment by oliversalzburg** [comment]
Damn, I just realized that I was only checking/unchecking the individual filters under the "Filters" section, but didn't enable the feature itself :(

After enabling the overall feature, crafting messages are no longer logged. So, yay :D
