### ISSUE TITLE
Space buildings are not being constructed

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#263]
I noticed that a lot of my space buildings stop being constructed even though there are more than enough resources available.

The problem lies in [`singleBuildPossible`](https://github.com/cameroncondry/cbc-kitten-scientists/blob/master/kitten-scientists.user.js#L1898-L1903), which returns `false` for the `oil` price.

I assume this is because the effect of space elevators is not taken into account.

@Wymrite I assigend you because you worked on this area of the code last.

**Comment by Wymrite** [comment]
Seems to be all oil price calculation for space buildings, not just singleBuildPossible. Will get a fix out soonish.

**Comment by Wymrite** [comment]
I think we can safely say that #266 fixed the issue for now.
