### ISSUE TITLE
Something is not right with the space mission unlocks

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#267]
The space mission was ultimately conducted as expected, but it appears something was not working right until then.

![image](https://user-images.githubusercontent.com/1658949/68604360-93de6b00-04aa-11ea-8bbc-66cfffc7ba12.png)

**Comment by oliversalzburg** [comment]
![image](https://user-images.githubusercontent.com/1658949/68850429-4e04eb00-06d4-11ea-8e70-268a40310782.png)

This always happens when the Space tab isn't active. As soon as I go to the Space tab, the mission is unlocked properly and the message is no longer logged.

**Comment by Wymrite** [comment]
Sounds like a tab render call is needed somewhere.

**Comment by oliversalzburg** [comment]
@Wymrite Yeah, I'm wondering why this seemed to work fine so far though. But I'll try to get a closer look soon. I'm in the process of moving to a new place though. So I wasn't able to take the required time off yet :(

**Comment by Wymrite** [comment]
Finally got around to this, seems like it did just need a tab render call. Should be fixed as of latest commit.
