### ISSUE TITLE
How do I set it to only craft when the base resource is full or almost full?

### ISSUE THREAD

**Issue by ixanza** [cameroncondry/cbc-kitten-scientists#269]
I'm looking at my log right now and all I can see is 

> Kittens have crafted 3.52 Beam
> Kittens have crafted 7.04 Slab
> Kittens have crafted 3.52 Beam
> Kittens have crafted 3.52 Beam
> Kittens have crafted 3.52 Slab
> Kittens have crafted 3.52 Beam
> Kittens have crafted 3.52 Beam
> Kittens have crafted 3.52 Slab
> Kittens have crafted 3.52 Beam
> Kittens have crafted 3.52 Slab
> Kittens have crafted 7.04 Beam
> Kittens have crafted 3.52 Slab
> Kittens have crafted 3.52 Beam

And this happens when they're at 20k/80k resources
How do I set it to trigger the craft when my wood/minerals are at or close to cap?

**Comment by Wymrite** [comment]
To keep the log clean, you can either disable limited crafting for those resources or you can enable KS's crafting filter. Disabling limited crafting for these resources will cause it to only trigger when it's above the set trigger value, but it won't help the log spam later on when storage caps are hit every few ticks so I'd recommend enabling the crafting filter.
