### ISSUE TITLE
Auto Festival seems to spam festival without actually making a festival

### ISSUE THREAD

**Issue by Azulan** [cameroncondry/cbc-kitten-scientists#27]
I don't know if it's just me, but the script will just keep posting the festival message, but the ui shows that there is no festival going on. Particularly when it's parchment limited.

**Comment by cameroncondry** [comment]
You are correct, I'll be working in a correction on this next patch.

**Comment by sjdrodge** [comment]
Correct me if I'm wrong, but does this only occur if you haven't yet researched Drama and Poetry?

**Comment by cameroncondry** [comment]
This issue appears to be corrected on my end. Refresh the script and you should see this error go away @Azulan.
