### ISSUE TITLE
Kitten scientist not working at all

### ISSUE THREAD

**Issue by DracosDeath** [cameroncondry/cbc-kitten-scientists#280]
kitten scientist appears to be crashing with the following error in the console:

kitten-scientists.user.js:1945 Uncaught TypeError: game.getLimitedDR is not a function
    at BulkManager.getPriceRatio (kitten-scientists.user.js:1945)
    at BulkManager.bulk (kitten-scientists.user.js:1821)
    at Engine.build (kitten-scientists.user.js:860)
    at Engine.iterate (kitten-scientists.user.js:466)

Both the main pages and alpha are affected
only the Obesevre the Sky function works at all
edit: it appears that research functions also still work, just everything with a "limited" option doesnt

**Comment by AirDur** [comment]
Do you use the new mainline http://kittensgame.com/web/# ?

**Comment by DracosDeath** [comment]
i was not aware. i have been using http://bloodrizer.ru/games/kittens/# and did not know there was a new site
