### ISSUE TITLE
Bookmarklet links to KS 1.4.2 instead of newest 1.5.0. Also instructions on using the newest version without the bookmarklet.

### ISSUE THREAD

**Issue by gearheaded** [cameroncondry/cbc-kitten-scientists#293]
Just an FYI -  the current bookmarklet at https://cdn.jsdelivr.net/gh/cameroncondry/cbc-kitten-scientists@master/kitten-scientists.user.js is version 1.4.2 of KS, instead of the newly updated KS 1.5.0. Anyone using Greasemonkey/Tampermonkey should automatically be updated to 1.5.0, but the CDN link is out of date. You may possibly have not yet updated it for testing purposes, but I figured I'd post this issue just in case you forgot. Cheers!

For anyone wishing to use the newest version in the meantime, you can copy the code from kitten-scientists.user.js and paste it into the console of the Developer Tools of your browser. To open Developer Tools in Firefox or Chrome, press SHIFT+CTRL+J. Click on "Console" at the top, and then paste the code and hit Enter.

Or, you can use also Greasemonkey or Tampermonkey to automatically load the newest version straight from Github every time you open Kittens Game. Note that the script is setup to only work on http://kittensgame.com/web/ - If you want to use the alpha or beta versions of Kittens Game with Kitten Scientists through Tampermonkey (the process may be similar for Greasemonkey, but I'm not positive as I don't use it) then after you install the Kitten Scientists script, you'll need to go into the Tampermonkey options by right clicking on the icon, then click on "Installed Userscripts", then "Edit" for Kittens Scientists (the second icon from the right on the far right side under "Actions" is the "Edit" button). It'll take you to the Editor where you'll see all of the code for the script. Click "Settings" at the top, next to "Editor". Then within the "Includes/Excludes" section, hit "Add" under "User Includes", and enter "*kittensgame.com/alpha/*" (without the quotes) and hit "OK", and then hit "Add" again and enter "*kittensgame.com/beta/*" (again without the quotes) and hit "OK". Now it will work automatically with any version!

**Comment by cameroncondry** [comment]
@gearheaded Thank you for pointing that out! I don't personally play much anymore and just directly use the script when testing new PRs. I'll have to see why that doesn't get auto updated properly. Ideally people should just point to master, but then again I usually merge straight into master instead of doing proper point releases.

**Comment by cameroncondry** [comment]
Found a purge cache url offered by jsdelivr: https://purge.jsdelivr.net/gh/cameroncondry/cbc-kitten-scientists@master

Thanks again for the report!
