### ISSUE TITLE
Bonfire buildings not triggering?

### ISSUE THREAD

**Issue by tehkingo** [cameroncondry/cbc-kitten-scientists#321]
Hi, 

I'm a new user of this script, and have been having difficulty getting Buildings to auto-build.  I've tried a bunch of triggers from 0 to various ranges up to 0.95, tried auto disabling them all and only turning on select ones, tried messing with the maximum to see if that was it, but no luck.

Reloading the script didn't help either.  

Some cursory googling suggests that this was an issue in the past that maybe was related to the enable all button, but I made sure to not use that button.

All other features of the script seem to work fine.

Any help would be appreciated.

**Comment by tehkingo** [comment]
PEBCAK

I was trying to use the script on an older version of the game.

Works fine on new version.

**Comment by cameroncondry** [comment]
Resounding success! Glad to hear it is working on your end. Thank you for the ticket and feel free to report any other issues you may find. There is a great group of people here that help keep the script up to date!
