### ISSUE TITLE
fastHuntContainer is deprecated

### ISSUE THREAD

**Issue by bloodrizer** [cameroncondry/cbc-kitten-scientists#327]
https://github.com/cameroncondry/cbc-kitten-scientists/blob/8f6c22f4d45a56324adc4913b2a6922e7a9f6734/kitten-scientists.user.js#L2029

Please use (catpower.value >= 100) && (!game.challenges.isActive("pacifism")) for fastHunt mode detection for a time being.
I will provide ui.isFastHuntAvailable() method in the next beta update.

https://discord.com/channels/392946190607581184/395596016188915722/854619937078509578

**Comment by oliversalzburg** [comment]
Thanks for bringing this up and providing the working code.
