### ISSUE TITLE
Auto-hunt seems to be not working

### ISSUE THREAD

**Issue by clemherreman** [cameroncondry/cbc-kitten-scientists#328]
Hello !

Thank you for KittenScientists :)

As of today, I noticed the auto-hunt does not seem to be working. Not console error log, but when catpower is full, the hunting is not triggered.

I'd like to help fixing it, but front JS is really not my expertise :x

My export, if needed to reproduce : https://gist.github.com/clemherreman/b61df881a5b19026a5ed23832dec134e
I guess it might be related to #327 but I feel it is a deprecation for the next version or the beta.

FWIW, I found another player, on discord, experiencing the same issue.

Thanks again for your time.

**Comment by clemherreman** [comment]
Also, I think auto-trade is broken too

**Comment by oliversalzburg** [comment]
I merged #326 to fix this. I will close this ticket, as it refers to hunting specifically. Please open a new ticket for trading, if that is still an issue.
