### ISSUE TITLE
Bookmarklet link for scientists is not working

### ISSUE THREAD

**Issue by NotISAE** [cameroncondry/cbc-kitten-scientists#341]
Recently I've been having issues with the bookmarklet on the newest version. When I use the old version at [http://bloodrizer.ru/games/kittens/#](url), the link works as normal. But when I then try on the new version, nothing happens.

**Comment by oliversalzburg** [comment]
What do you mean when you refer to the "new version". Could you supply me with a link?

**Comment by NotISAE** [comment]
[kittensgame.com/web/#](url) the main game, Version 1.4.9.1

**Comment by oliversalzburg** [comment]
Not sure what is happening on your end, but the bookmarklet works perfectly fine on that site for me.

**Comment by NotISAE** [comment]
Scientists doesn't work but another one i have works
https://user-images.githubusercontent.com/105261543/168160014-62b75c22-6878-4e64-88a0-03d38e78cdec.mp4

**Comment by oliversalzburg** [comment]
Thanks for the recording. That is very helpful. I noticed that you copied the bookmarklet from the page, but then activated your existing bookmarklet on the bookmark bar. I'm sure you created it carefully, but I would really have to see the bookmarklet itself or see you create it to see that there aren't any mistakes being made.

That being said, if at all possible, I recommend using a userscript manager anyway.

You can also paste the bookmarklet into the JavaScript console, if that is any help.

**Comment by NotISAE** [comment]
I tried on a new computer, and it worked. Sorry for the trouble
