### ISSUE TITLE
Kitten resources missing

### ISSUE THREAD

**Issue by dethmourne** [cameroncondry/cbc-kitten-scientists#342]
The Kitten Resources category seems to be missing entirely from the latest update.

![image](https://user-images.githubusercontent.com/14261370/179514487-6510515a-695a-40c0-b377-889e57a8e00f.png)

**Comment by oliversalzburg** [comment]
As the script hasn't been updated in a year, this seems somewhat unlikely. The latest version is also 1.5.0, not 1.4.2.
