### ISSUE TITLE
add support for some space tab options

### ISSUE THREAD

**Issue by jacob-keller** [cameroncondry/cbc-kitten-scientists#35]
I'd like to see some support in the future for managing space options. Specifically, I think the biggest addition would be a way to re-enable the lunar outposts when uranium is full. This would be a handy feature for during the time when uranium production is vastly below the cost to make unobtainium. This is something that prevents advance, because I have to keep re-enabling the outposts when I obtain more unobtanium.

I couldn't think of an easy way to sneak that into the setup now, but I hope this can be something to remember for future enhancements.

**Comment by cameroncondry** [comment]
Would definitely be nice in the future. I would also like to see kitten population management, however, I haven't even begun looking into how that would work.

**Comment by DirCattus** [comment]
Hmmm... To do the unobtanium, have it turn on one (or all) lunar outposts when uranium >= 95% of maximum, and turn it off when uranium <= 5% of maximum.

**Comment by jacob-keller** [comment]
They already automatically turn off when near empty but yea that seems
useful.

I have a suggested way:

When at 95% turn them on until uranium is negative. Them at 5% turn them
off until it is positive.

Also turn them all off if unobtainable is full.

That way if you do produce enough uranium to keep one on, it will still run.

**Comment by jacob-keller** [comment]
With the addition of the new update, this has fallen on my backburner, since they gave us a much better way to produce the necessary uranium. It's something I'd to see, but much less personal interest in for now.

**Comment by eringrand** [comment]
With new update, there's also a a new material to add to the crafting list.

**Comment by jacob-keller** [comment]
Yep, we should at least have eludium in the list now :)
