### ISSUE TITLE
Add timer to stop overcrafting of limitless items

### ISSUE THREAD

**Issue by DirCattus** [cameroncondry/cbc-kitten-scientists#37]
When I have autocrafting enabled for an item (such as concrete), it will create too many of the items. I feel this is because there isn't an upper limit to check against.

For the items that do not have an upper limit on their components (concrete, ships, etc), would it be possible to have a timer attached to them so that they are autocrafted (say) just once a season or two?

![kittenslimits](https://cloud.githubusercontent.com/assets/12201332/7520779/cf158d72-f4ae-11e4-8f4e-97e731faefd5.jpg)

(Also, autotrading seems to do something similar with the spiders and nagas and the like. The items they want don't have an upper limit, so it seems like I am sending out several caravans one group right after the other.)

**Comment by pefoley2** [comment]
I've also run into this issue, and it's caused problems with building up a stock of starcharts and other things.

**Comment by cameroncondry** [comment]
That is a really good suggestion, only allowing it to trade once per season if there is no upper limits! I think this should be implemented.

**Comment by jacob-keller** [comment]
Agreed! That is a simple way to fix them without having to add limits or
prevent all auto trades.

I think that would resolve a lot of issues.

I can look at coding something like that up.

**Comment by andrealessi** [comment]
It might be a bit fiddly, but if a once-per-season rule for crafting these items were to be implemented, maybe there should also be a check based on the current total of the component resource(s) to prevent overcrafting?  So gears would only be crafted if the current number of gears is less than 50%/25%/10% of total steel at the time of the check.  

What's happening at the moment is that gear crafting is completely clearing out steel, leaving other items that also use steel (alloy, concrete, etc) to never be crafted, and producing an oversupply of gears.

**Comment by jacob-keller** [comment]
I'm trying to think of a good way to resolve that issue. One solution is provide a maximum value that can be created at a time so that it will then try others again as well.. It  gets really complicated, so some sort of checking needs to occur.

I like the "each thing only once per season" so that even if gears consume half the steal once, they won't be allowed again until the season after.
