### ISSUE TITLE
Log entries are missing

### ISSUE THREAD

**Issue by DrGaellon** [cameroncondry/cbc-kitten-scientists#48]
About a day or so ago, I noticed that the log entries for automated activity, which used to appear in purple, have disappeared. Now, I only get the entries for astronomical events, which are in grey text. It also tells me (in blue) about blueprints and titanium when I trade. If I click "show activity," it gives me a summary (in purple) of everything the script has done since the last time I clicked it, but the line entries are gone.

**Comment by jacob-keller** [comment]
Yep that was an intentional change.

**Comment by DrGaellon** [comment]
Oh. :( I liked it better the other way - personal preference.

**Comment by jacob-keller** [comment]
We could make it periodically display activity.. the general problem I had
with the method was how easily information was lost.

**Comment by DrGaellon** [comment]
I can see that. Maybe leave the log entries in, and also allow for the summary on demand?

**Comment by cameroncondry** [comment]
I like the issue of leaving the log entries in, as well as offering the summary on demand. Could add a simple option that would allow to turn off the constant log messages.

**Comment by jacob-keller** [comment]
#47 should now have a solution in place for this. I realize that #47 is growing fast, but I really didn't like having to work separately and leave rebase/merge issues later.

**Comment by DrGaellon** [comment]
Is this change live if I reload the script? (I know nothing about scripting and Github flows.)

**Comment by jacob-keller** [comment]
Nope sorry not yet. I only proposed it in part of my enhancements pull
request.

I think that Cameron will likely pull it sometime in the next 24 hours but
I am not sure since the pull request has gotten very large and not easy to
separate out.

So far with my testing everything has been good but I am not sure his
thoughts on everything.

**Comment by cameroncondry** [comment]
This has been implemented on the latest master branch. I will update the changelog with the details at a later date. Thank you for the suggestions!
