### ISSUE TITLE
Toggle to enable/disable all options

### ISSUE THREAD

**Issue by cameroncondry** [cameroncondry/cbc-kitten-scientists#51]
I would like to see a toggle to enable/disable all items in a list. For instance, I currently want to just build all buildings, and it would be nice to have a toggle all button to enable them all. The saving update would also help remedy the need to reset all options after a game update, as that is usually when I reload the page.

**Comment by jacob-keller** [comment]
That is something I think should be easy to do. Saving is definitely a bit
addition I would like to see.

**Comment by jacob-keller** [comment]
This can probably be closed now.

**Comment by jacob-keller** [comment]
This has been merged we have buttons to clear all options. There isn't one for disabling all the main checklists, but I figured this is probably ok since there are far fewer options here. If you think it's necessary I can add one for consistency.

**Comment by oliversalzburg** [comment]
@cameroncondry Would you mind closing this?
