### ISSUE TITLE
Page redirect protection

### ISSUE THREAD

**Issue by cameroncondry** [cameroncondry/cbc-kitten-scientists#52]
I would like to see a notification pop up warning a user if a link is going to load in the same window. The main reason for this is the interface links will option in the same tab in most cases and will cause the user to need to reload the script and game.

**Comment by jacob-keller** [comment]
I am not sure what we have to protect against this..

**Comment by cameroncondry** [comment]
After thinking about it a bit, the real issue is just the reddit/wiki links that don't open in new tabs. It may be a simple enhancement to just add target="_blank" to any external links in the system.

**Comment by jacob-keller** [comment]
Sounds reasonable

**Comment by oliversalzburg** [comment]
Is this still an issue? `$("a[target!='_blank']").not("a[href$='#']")` returns an empty array. So either all external links target `_blank` or my selector is off ;D

**Comment by oliversalzburg** [comment]
@cameroncondry This seems to no longer be an issue. Would you mind closing it?
