### ISSUE TITLE
KS options menu no longer visible 

### ISSUE THREAD

**Issue by andrealessi** [cameroncondry/cbc-kitten-scientists#54]
Unless I'm missing something horribly obvious, the most recent merge has hidden the options menu from the activity log?  Can't get the script to restart after a page refresh without using the console.

It was visible on a previous refresh about an hour or two earlier.

**Comment by jacob-keller** [comment]
I can take a look

**Comment by jacob-keller** [comment]
Accidentally used an incorrect variable, cleared it up so the options should appear again now.
