### ISSUE TITLE
Kittens dying...

### ISSUE THREAD

**Issue by DirCattus** [cameroncondry/cbc-kitten-scientists#59]
It looks like the latest version of the code has a bug in it that is converting enough catnip that it goes into the negatives. This kills all of the kittens instantly, plus several thousand in the countryside around the city. (I had 32k die in a town that had 83 kittens, for example.)

**Comment by andrealessi** [comment]
This seems to coincide with Pastures being built, although I don't know if it's related.

**Comment by jacob-keller** [comment]
Uhoh.

**Comment by pefoley2** [comment]
I have auto-building disabled, and I'm seeing negative values for catnip as well.

**Comment by jacob-keller** [comment]
Yea, there  was a type in getValueAvailable where we divided by consume instead of multiplied. I have a pull request to fix this now.

**Comment by jacob-keller** [comment]
Should be fixed by #60

**Comment by jacob-keller** [comment]
This has been fixed in master branch now.

**Comment by cameroncondry** [comment]
Thank you for the correction @jacob-keller.
