### ISSUE TITLE
Leviathans trade not executing

### ISSUE THREAD

**Issue by pefoley2** [cameroncondry/cbc-kitten-scientists#61]
The leviathan trades seem to be triggering but not actually executing.
I'm getting stuff like "Trade 18x Leviathans" in the log, but the trade doesn't actually execute and provide time crystals.

**Comment by jacob-keller** [comment]
Interesting. Is this occurring with other races?

**Comment by pefoley2** [comment]
Trades w/ Zebras seem to be fine.

**Comment by jacob-keller** [comment]
Have you updated to the latest master branch? We fixed an issue where leviathans were checking their sorrow cap and refusing to trade because it was full.

**Comment by pefoley2** [comment]
Yeah I have. The problem now seems to be that kitten scientists thinks it's executing the trade, but the game core doesn't register it for some reason.

**Comment by jacob-keller** [comment]
Ok.

what browser are you running? Are you comfortable with a debugger?

I can't do much more yet as I don't have access to leviathan yet.

**Comment by pefoley2** [comment]
Chrome. I can use a debugger.
You could always use a incognito mode instance to give yourself leviathans as well :)

**Comment by jacob-keller** [comment]
try running

t = new TradeManager()
t.getLowestTradeAmount('leviathans')

and see how much it returns. If it's not zero, does that number make some
sense given how much unobtanium you have?

if so, try running

debugger ; t.trade('leviathans', <number>)

and step through to see where it might actually be failing.

**Comment by pefoley2** [comment]
With a full stock of 7.9K unobtanium and the trade button available i'm still getting 0 for the trade amount.

**Comment by jacob-keller** [comment]
Please re-try this on master branch again and see if it fixed.

**Comment by pefoley2** [comment]
I'm still getting 0 for the trade amount, and it doesn't seem to be trading.

**Comment by jacob-keller** [comment]
try stepping through the debugger on:

t = new TradeManager()
t.getLowestTradeAmount('leviathans')

and see where it sets it to 0. That'd be great help.

**Comment by pefoley2** [comment]
It looks like options.consume=0.6 is maxing out the available unobtanium for trading at 4788 for a cap of 7980.

**Comment by jacob-keller** [comment]
ahhh hmm Not sure the best way to resolve that. We don't want to consume everything from all resources...

**Comment by pefoley2** [comment]
Maybe have a per-race value and set it really low for leviathans?

**Comment by jacob-keller** [comment]
I'd defer to Cameron on what the best fix for this would be. That sounds easy to implement though.

**Comment by cameroncondry** [comment]
I'm really leaning towards the idea of giving each resource a consume amount. There are multiple resources that would benefit from consuming more than 60% of the resource.

**Comment by jacob-keller** [comment]
Ok. That wouldn't be hard.

Should it be per craft/trade or per resource?

**Comment by cameroncondry** [comment]
Good question, I'm inclined to say per resource, as it would be nice to set the consume amounts next to the ability to set the stocks.

**Comment by jacob-keller** [comment]
I added a per-resource consume rate control, and default unobtainium to using up all of its value.

**Comment by oliversalzburg** [comment]
Leviathan trade is working fine for me. I'd say this can be closed if nobody disagrees.
