### ISSUE TITLE
Concrete limit becomes misspelled on being set

### ISSUE THREAD

**Issue by simonhollingshead** [cameroncondry/cbc-kitten-scientists#69]
Just a UI oddity:

Crafting > Stocks > Add Stock > Concrete

"Concrete: 0"

Click it.

"Stock for **concrate**"

Enter '1'.

"**Concrate** : 1"

**Comment by jacob-keller** [comment]
it displays the internal name. Not the title. We should probably fix that..

**Comment by oliversalzburg** [comment]
I don't even see a **Stock** option. Can this still be reproduced?

**Comment by simonhollingshead** [comment]
The option is there (Crafting > Resources > Add Concrete > Click the 'Stock 0') but now it no longer has an issue.  Closed.
