### ISSUE TITLE
Buildings aren't being built in Iron Will mode

### ISSUE THREAD

**Issue by eringrand** [cameroncondry/cbc-kitten-scientists#70]
I don't know what's going on, but my wood and catnip are sitting at cap without building fields or Libraries, despite having the materials available to do so.

**Comment by jacob-keller** [comment]
Have you set any stocks? Are they have the buildings enabled I assume?

**Comment by eringrand** [comment]
I don't have any stocks and the buildings are enabled.

**Comment by jacob-keller** [comment]
Ok. Try poking around at BuildManager in the console might help.

**Comment by jacob-keller** [comment]
Ok, so the issue is that the buildings are checking for resource consume rate, so it honors this and won't build a building if it takes more than 60% of the total value. I'm working on a small fix to make buildings ignore this, since we normally want them to.

**Comment by oliversalzburg** [comment]
@jacob-keller Did you already fix this by any chance? I didn't notice any issues when I played IW.

**Comment by Wymrite** [comment]
Buildings currently ignore resource consumption rate.
