### ISSUE TITLE
Very little auto building/crafting/hunting/etc after last update

### ISSUE THREAD

**Issue by andrealessi** [cameroncondry/cbc-kitten-scientists#73]
Console error (repeating constantly) is: 

Uncaught TypeError: Cannot read property 'consume' of undefined
CraftManager.getValueAvailable @ kitten-scientists.js:552
CraftManager.getLowestCraftAmount @ kitten-scientists.js:483
Engine.craft @ kitten-scientists.js:263
Engine.iterate @ kitten-scientists.js:225

Looks like this issue sneaked in with the latest update.  Prevents most auto building/crafting/trading/praising, but not everything oddly enough (once beams are crafted manually, warehouses are built; once steel is available, gears are crafted, etc.)

**Comment by jacob-keller** [comment]
Hmmmmm

**Comment by cameroncondry** [comment]
Will keep this open for a day or two, but the issue should be corrected on master. Thanks for the report @andrealessi and the quick fix @jacob-keller .

**Comment by andrealessi** [comment]
Seems to be working brilliantly, thanks!

**Comment by jacob-keller** [comment]
Excellent =]

**Comment by cameroncondry** [comment]
Glad everything looks to be working well, closing this issue, thanks again!
