### ISSUE TITLE
Use localStorage to save resource/item settings

### ISSUE THREAD

**Issue by magus424** [cameroncondry/cbc-kitten-scientists#75]
Would be nice to not have to reconfigure the scientists every time I have to restart my browser or refresh the page :)

**Comment by cameroncondry** [comment]
I definitely agree, would be a great addition.

**Comment by magus424** [comment]
@cameroncondry, looking at possibly adding support for this, but wanted to ask a style question before I get too far in; any objection to alignment of various objects? I'm doing it for myself to better understand what is set where, but wondered if I would need to trim it when it comes time to commit/PR :)

ex: ![](http://i.imgur.com/Ascjf6J.png)

**Comment by jacob-keller** [comment]
That looks fine to me.

**Comment by cameroncondry** [comment]
I don't mind the alignment, it does help the visibility of everything. One day I will install an auto alignment plugin so I don't have to manually align everything. ;)

**Comment by magus424** [comment]
If you use vim, [vim-easy-align](https://github.com/junegunn/vim-easy-align) is a nice one :)

**Comment by cameroncondry** [comment]
This looks great and will be merged into master within the day.
