### ISSUE TITLE
Trading bug?

### ISSUE THREAD

**Issue by DrGaellon** [cameroncondry/cbc-kitten-scientists#76]
I noticed that even when I don't have any trades selected for Autumn, the script auto-trades any race I have selected at all. I also noted that the season is misspelled as "Autunn" under every race. Is this misspelling causing a check to fail somewhere, allowing trading to occur even when not desired? (I'm not skilled enough to read the code myself.)

**Comment by jacob-keller** [comment]
Very possibly

**Comment by DrGaellon** [comment]
Fixing the spelling error fixed the problem. :)
