### ISSUE TITLE
Not working in 1.1.1.5

### ISSUE THREAD

**Issue by jamesbascle** [cameroncondry/cbc-kitten-scientists#83]
Doesn't seem to be auto-building, hunting, crafting, or anything else after the new versions released in the past few days.

**Comment by cameroncondry** [comment]
I was running the system fine last night, but will be unable to test until later tonight. Be sure to enable the settings that you want to automate and try testing the script a few times.

**Comment by jamesbascle** [comment]
Alrighty.  I basically loaded up a save into 1.1.1.5 from 1.1.0.9 late last night, used the bookmarklet to inject the script into the page, and then left.  This morning i was full on resources... I'll do some more digging.

**Comment by jamesbascle** [comment]
Hmm, after doing it all again, it does seem to be auto build/crafting now.  I'll close!
