### ISSUE TITLE
Holding a festival before it's unlocked

### ISSUE THREAD

**Issue by JohnDoee** [cameroncondry/cbc-kitten-scientists#85]
It seems to be able to trigger festivals before they're actually unlocked.

**Comment by cameroncondry** [comment]
I just noticed that as well. It seems the game's code unlocks the festivals before you actually see the button on the interface. I will have to see if there is another check I can do before holding festivals, since this can be seen as slightly cheating.

**Comment by oliversalzburg** [comment]
Is this still an issue? If so, checking `game.villageTab.festivalBtn.visible` should be fine IMHO.

**Comment by cameroncondry** [comment]
That should solve the issue, however, I haven't personally checked up or added anything to do the checking.

**Comment by oliversalzburg** [comment]
I haven't run into this myself. I'm currently right before researching **Drama and Poetry** in one of my games and I'm not seeing any festivals in the log. I'm not sure how this error condition would be triggered.

**Comment by JohnDoee** [comment]
You just need enough resources and it should trigger, if the festival triggering logic isn't changed.

**Comment by oliversalzburg** [comment]
@JohnDoee I'll try to max out before researching **Drama and Poetry**. Let's see :) I'll report back …if I don't accidentally click that upgrade ;D

**Comment by oliversalzburg** [comment]
Actually, I could already satisfy the resource requirements and there is a check for `game.science.get('drama').researched`, which results in `false` for me. So the other checks aren't even relevant and once I research drama, I will also get the button.

So, I don't see how this could happen right now.

**Comment by oliversalzburg** [comment]
I guess this was fixed by https://github.com/cameroncondry/cbc-kitten-scientists/commit/97012885295276b04d4d8fb82448a1a40a683297

**Comment by cameroncondry** [comment]
Oh, nice detective work! I definitely merged that in but it slipped my mind.
