### ISSUE TITLE
Plates not being crafted?

### ISSUE THREAD

**Issue by andrealessi** [cameroncondry/cbc-kitten-scientists#87]
I'm not sure when it started, but as of right now, plates aren't being crafted from iron, even at max (or above max) iron capacity.

I've tried disabling smelters and calciners to reduce the per second production below the maximum (current capacity is at 12.178M, producton is +20.666M/sec with everything turned on.)  I've also tried turning off Steamworks (I have Workshop Automation and Pneumatic Press researched) but this doesn't seem to make a difference.  I've also tried disabling/reenabling the related option checkboxes. I've set stock to 0 and consume to 1.00. 

Beams and slabs are being produced fine, as is steel, and buildings that require iron.

**Comment by andrealessi** [comment]
Weirdly enough, disabling steel crafting is what seems to allow plate crafting.

**Comment by jacob-keller** [comment]
Steel uses iron.

**Comment by cameroncondry** [comment]
To elaborate a bit, if your coal production is higher than your iron production, and you have steel and plates enabled, then it will only ever produce steel. Coal will trigger first at max capacity, making it improbable for iron to ever hit cap and trigger plate production. I'm on a new play-through currently, and plates are producing.

**Comment by jacob-keller** [comment]
You can fix this by using the varying resource cap controls to help get
utilization correct.

The system for determining what to do is not really capable of knowing
whether you want steel or plates, and it doesn't try to prioritize things.
