### ISSUE TITLE
Not Auto Hunting?

### ISSUE THREAD

**Issue by rclough** [cameroncondry/cbc-kitten-scientists#91]
Browser: Chrome
OS: Mac OSX 10.10

Replicate:

1. Hard refresh kittensgame
2. Click my bookmarklet (copy pasted from github readme)
3. KS UI loads
4. Uncheck everything except hunting
5. Wait until catpower maxes out
6. Auto hunt never happens

Not sure how else to help further debug the issue. I've a moderate understanding of JS but not enough to go digging myself, but happy to follow instructions.

Other context: I have never used KS before, so its not like this was working and broke at some point for me. I mostly only want auto hunts, but I was gonna try some of the features after trying out auto-hunt

**Comment by oliversalzburg** [comment]
Auto-Hunts are working fine for me. You *do* have **Engine** checked, right?

**Comment by rclough** [comment]
Looks like you solved it.

In my defense, naming the starting function "engine" and mentioning it nowhere in the readme is a bit of a poor user experience choice. I probably assumed it was some functionality I hadn't unlocked in the game, so I didnt want it on yet....

**Comment by oliversalzburg** [comment]
I agree. I was confused by this as well when I started using the script. I proposed https://github.com/cameroncondry/cbc-kitten-scientists/pull/103 to make the function of the checkbox clearer.

**Comment by cameroncondry** [comment]
Thank you @oliversalzburg for making this more clear. The README is terribly outdated at this point, quite a few new and updated features that aren't reflected there.
