### ISSUE TITLE
Doesn't build pastures

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#95]
I noticed this for a while, pastures are not being built. I reset the game last night and let it run all night to confirm. Not a single pasture was built.

**Comment by oliversalzburg** [comment]
Code looks fine from what I can tell :\ I'll debug this in the evening and provide a PR if possible

**Comment by cameroncondry** [comment]
I haven't been in the system in quite some time now. However, I do know there were some new building upgrades for some buildings, which may effect the trigger to actually build those.

**Comment by oliversalzburg** [comment]
@cameroncondry Yeah, seems to be related to the different stages of buildings. I'll send a PR momentarily.

**Comment by oliversalzburg** [comment]
I'll also try to finally try that other open PR, but it looks like a pretty reasonable change from what I can tell by looking at the code.

**Comment by cameroncondry** [comment]
Thank you for looking into and fixing the issue, definitely appreciated.
