### ISSUE TITLE
Order of buildings

### ISSUE THREAD

**Issue by oliversalzburg** [cameroncondry/cbc-kitten-scientists#98]
Would there be interest in merging a change that allows reordering of buildings to affect the priority at which they are built?

I noticed that the scientists will always max out academies and observatories before building, for example, huts and houses, which I consider suboptimal. This is obviously due to the order in which they are defined in the `build` array.

I would propose adding the ability to affect the order, so that you can prioritize builds. I'd be happy to implement this if there's a chance to have it merged upstream :)

**Comment by cameroncondry** [comment]
I would definitely be interested in seeing some changes like the ones you listed. Currently I am not actively developing, however, I do merge in requests to the system fairly actively. My two requests with PRs is to be sure to test the system and keep close to the code style already implemented.

**Comment by oliversalzburg** [comment]
Will do! :)
